from .task_01_distance import *
from .task_02_circle import *
from .task_03_operations import *
from .task_04_movies import *
from .task_05_family import *
from .task_06_zoo import *
from .task_07_songs import *
from .task_08_secret import *
from .task_09_garden import *
from .task_10_shopping import *
from .task_11_store import *